services:
  _defaults:
    autoconfigure: true

  rhyme_be.listener.copy_images_for_element_sets:
    class: Rhyme\ContaoBackendThemeBundle\EventListener\CopyImagesForElementSets
    arguments:
      - '@contao.framework'
      - '%contao.web_dir%'
      - '@filesystem'
    tags:
      - { name: kernel.event_listener, event: contao.generate_symlinks }
    public: true

  rhyme_be.listener.backend_menu:
    class: Rhyme\ContaoBackendThemeBundle\EventListener\BackendMenuListener
    arguments:
      - '@security.helper'
      - '@router'
      - '@request_stack'
      - '@translator'
      - '%kernel.debug%'
      - '%contao_manager.manager_path%'
      - '@?contao_manager.jwt_manager'
    tags:
      - { name: kernel.event_listener, event: contao.backend_menu_build }
    public: true

  rhyme_be.listener.load_element_sets:
    class: Rhyme\ContaoBackendThemeBundle\EventListener\LoadElementSets
    arguments:
      - '@event_dispatcher'
      - '%contao.resources_paths%'
      - '@contao.framework'
      - '@filesystem'
    tags:
      - { name: kernel.event_listener, priority: 333 }
    public: true

  Rhyme\ContaoBackendThemeBundle\EventListener\PageOperationsListener:
    arguments:
      - '@contao.framework'
      - '@security.helper'
      - '@database_connection'
    tags:
      - { name: contao.callback, table: tl_page, target: list.operations.articles.button, method: adjustPageOperations, priority: 400 }
    public: true
