services:

  rhyme_be.listener.copy_images_for_element_sets.php:
    class: Rhyme\ContaoBackendThemeBundle\EventListener\CopyImagesForElementSets
    arguments:
      - '@contao.framework'
      - '%contao.web_dir%'
      - '@filesystem'
    tags:
      - { name: kernel.event_listener, event: contao.generate_symlinks }
    public: true