services:

  contao.listener.store_referer:
    class: Rhyme\ContaoBackendThemeBundle\EventListener\StoreRefererListener
    arguments:
      - '@security.helper'
      - '@contao.routing.scope_matcher'
    tags:
      - kernel.event_listener